var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "application_command.h", "application__command_8h.html", "application__command_8h" ],
    [ "audit_log.h", "include_2audit__log_8h.html", "include_2audit__log_8h" ],
    [ "auto_moderation.h", "include_2auto__moderation_8h.html", "include_2auto__moderation_8h" ],
    [ "channel.h", "include_2channel_8h.html", "include_2channel_8h" ],
    [ "concord-once.h", "concord-once_8h.html", "concord-once_8h" ],
    [ "discord-events.h", "discord-events_8h.html", "discord-events_8h" ],
    [ "discord-internal.h", "discord-internal_8h.html", "discord-internal_8h" ],
    [ "discord-request.h", "discord-request_8h.html", "discord-request_8h" ],
    [ "discord-response.h", "discord-response_8h.html", "discord-response_8h" ],
    [ "discord-worker.h", "discord-worker_8h.html", "discord-worker_8h" ],
    [ "discord.h", "discord_8h.html", "discord_8h" ],
    [ "emoji.h", "include_2emoji_8h.html", "include_2emoji_8h" ],
    [ "gateway.h", "include_2gateway_8h.html", "include_2gateway_8h" ],
    [ "guild.h", "include_2guild_8h.html", "include_2guild_8h" ],
    [ "guild_scheduled_event.h", "include_2guild__scheduled__event_8h.html", "include_2guild__scheduled__event_8h" ],
    [ "guild_template.h", "include_2guild__template_8h.html", "include_2guild__template_8h" ],
    [ "interaction.h", "interaction_8h.html", "interaction_8h" ],
    [ "invite.h", "include_2invite_8h.html", "include_2invite_8h" ],
    [ "oauth2.h", "include_2oauth2_8h.html", "include_2oauth2_8h" ],
    [ "osname.h", "osname_8h.html", "osname_8h" ],
    [ "stage_instance.h", "include_2stage__instance_8h.html", "include_2stage__instance_8h" ],
    [ "sticker.h", "include_2sticker_8h.html", "include_2sticker_8h" ],
    [ "user.h", "include_2user_8h.html", "include_2user_8h" ],
    [ "voice.h", "include_2voice_8h.html", "include_2voice_8h" ],
    [ "webhook.h", "include_2webhook_8h.html", "include_2webhook_8h" ]
];