var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "application_command.h", "application__command_8h.html", "application__command_8h" ],
    [ "audit_log.h", "audit__log_8h.html", "audit__log_8h" ],
    [ "auto_moderation.h", "auto__moderation_8h.html", "auto__moderation_8h" ],
    [ "channel.h", "channel_8h.html", "channel_8h" ],
    [ "discord-cache.h", "discord-cache_8h.html", "discord-cache_8h" ],
    [ "discord-events.h", "discord-events_8h.html", "discord-events_8h" ],
    [ "discord-internal.h", "discord-internal_8h.html", "discord-internal_8h" ],
    [ "discord-request.h", "discord-request_8h.html", "discord-request_8h" ],
    [ "discord-response.h", "discord-response_8h.html", "discord-response_8h" ],
    [ "discord-worker.h", "discord-worker_8h.html", "discord-worker_8h" ],
    [ "discord.h", "discord_8h.html", "discord_8h" ],
    [ "emoji.h", "emoji_8h.html", "emoji_8h" ],
    [ "gateway.h", "gateway_8h.html", "gateway_8h" ],
    [ "guild.h", "guild_8h.html", "guild_8h" ],
    [ "guild_scheduled_event.h", "guild__scheduled__event_8h.html", "guild__scheduled__event_8h" ],
    [ "guild_template.h", "guild__template_8h.html", "guild__template_8h" ],
    [ "interaction.h", "interaction_8h.html", "interaction_8h" ],
    [ "invite.h", "invite_8h.html", "invite_8h" ],
    [ "oauth2.h", "oauth2_8h.html", "oauth2_8h" ],
    [ "osname.h", "osname_8h.html", "osname_8h" ],
    [ "stage_instance.h", "stage__instance_8h.html", "stage__instance_8h" ],
    [ "sticker.h", "sticker_8h.html", "sticker_8h" ],
    [ "user.h", "user_8h.html", "user_8h" ],
    [ "voice.h", "voice_8h.html", "voice_8h" ],
    [ "webhook.h", "webhook_8h.html", "webhook_8h" ]
];