#include "custom.pre.h"

#include "permissions.pre.h"
#include "application.pre.h"
#include "audit_log.pre.h"
#include "invite.pre.h"
#include "channel.pre.h"
#include "emoji.pre.h"
#include "guild.pre.h"
#include "guild_scheduled_event.pre.h"
#include "guild_template.pre.h"
#include "stage_instance.pre.h"
#include "sticker.pre.h"
#include "user.pre.h"
#include "voice.pre.h"
#include "webhook.pre.h"

#include "gateway.pre.h"
#include "teams.pre.h"
#include "voice_connections.pre.h"

#include "application_commands.pre.h"
#include "message_components.pre.h"
#include "interactions.pre.h"
