#ifndef GENCODECS_H
#define GENCODECS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Allow symbols usage without GENCODECS_ prefix */
#ifndef GENCODECS_USE_PREFIX
#define COND_INSERT GENCODECS_COND_INSERT

#define STRUCT_BEGIN GENCODECS_STRUCT_BEGIN
#define FIELD_CUSTOM GENCODECS_FIELD_CUSTOM
#define FIELD_PRINTF GENCODECS_FIELD_PRINTF
#define FIELD GENCODECS_FIELD
#define FIELD_STRUCT_PTR GENCODECS_FIELD_STRUCT_PTR
#define FIELD_PTR GENCODECS_FIELD_PTR
#define FIELD_ENUM GENCODECS_FIELD_ENUM
#define STRUCT_END GENCODECS_STRUCT_END

#define LIST_BEGIN GENCODECS_LIST_BEGIN
#define LISTTYPE_PRIMITIVE GENCODECS_LISTTYPE_PRIMITIVE
#define LISTTYPE_STRUCT GENCODECS_LISTTYPE_STRUCT
#define LISTTYPE_PTR GENCODECS_LISTTYPE_PTR
#define LIST_END GENCODECS_LIST_END

#define ENUM_BEGIN GENCODECS_ENUM_BEGIN
#define ENUM_END GENCODECS_ENUM_END
#define ENUMERATOR GENCODECS_ENUMERATOR
#define ENUMERATOR_END GENCODECS_ENUMERATOR_END
#endif /* GENCODECS_USE_PREFIX */

#endif /* GENCODECS_H */
