ENUM_BEGIN(discord_channel_types)
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_TEXT, = 0)
    ENUMERATOR(DISCORD_CHANNEL_TYPE_DM, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_VOICE, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GROUP_DM, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_CATEGORY, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_NEWS, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_STORE, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_NEWS_THREAD, = 11)
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_PUBLIC_THREAD, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_PRIVATE_THREAD, )
    ENUMERATOR(DISCORD_CHANNEL_TYPE_GUILD_STAGE_VOICE, )
ENUM_END(discord_channel_types)

STRUCT_BEGIN(discord_overwrite)
  COND_INSERT(id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, id)
    FIELD(int, type)
    FIELD_PRINTF(uint64_t, SCNu64, PRIu64, allow)
    FIELD_PRINTF(uint64_t, SCNu64, PRIu64, deny)
STRUCT_END(discord_overwrite)

LIST_BEGIN(discord_overwrites)
    LISTTYPE_STRUCT(discord_overwrite)
LIST_END(discord_overwrites)

STRUCT_BEGIN(discord_channel)
  COND_INSERT(id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, id)
    FIELD_ENUM(discord_channel_types, type)
  COND_INSERT(guild_id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, guild_id)
    FIELD(int, position)
  COND_INSERT(permission_overwrites, !=, NULL)
    FIELD_STRUCT_PTR(discord_overwrites, *, permission_overwrites)
  COND_INSERT(name, !=, NULL)
    FIELD_PTR(char, *, name)
  COND_INSERT(topic, !=, NULL)
    FIELD_PTR(char, *, topic)
    FIELD(bool, nsfw)
  COND_INSERT(last_message_id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, last_message_id)
  COND_INSERT(bitrate, !=, 0)
    FIELD(int, bitrate)
  COND_INSERT(user_limit, !=, 0)
    FIELD(int, user_limit)
  COND_INSERT(rate_limit_per_user, !=, 0)
    FIELD(int, rate_limit_per_user)
  COND_INSERT(recipients, !=, NULL)
    FIELD_STRUCT_PTR(discord_users, *, recipients)
  COND_INSERT(icon, !=, NULL)
    FIELD_PTR(char, *, icon)
  COND_INSERT(owner_id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, owner_id)
  COND_INSERT(application_id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, application_id)
  COND_INSERT(parent_id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, parent_id)
#if 0
  COND_INSERT(last_pin_timestamp, !=, 0)
    FIELD_PRINTF(u64unix_ms, last_pin_timestamp)
    FIELD_STRUCT_PTR(discord_messages, *, messages)
#endif
STRUCT_END(discord_channel)

ENUM_BEGIN(discord_user_flags)
    ENUMERATOR(DISCORD_DISCORD_EMPLOYEE, = 1 << 0)
    ENUMERATOR(DISCORD_PARTNERED_SERVER_OWNER, = 1 << 1)
    ENUMERATOR(DISCORD_HYPESQUAD_EVENTS, = 1 << 2)
    ENUMERATOR(DISCORD_BUG_HUNTER_LEVEL_1, = 1 << 3)
    ENUMERATOR(DISCORD_HOUSE_BRAVERY, = 1 << 4)
    ENUMERATOR(DISCORD_HOUSE_BRILLIANCE, = 1 << 5)
    ENUMERATOR(DISCORD_HOUSE_BALANCE, = 1 << 6)
    ENUMERATOR(DISCORD_EARLY_SUPPORTER, = 1 << 7)
    ENUMERATOR(DISCORD_TEAM_USER, = 1 << 8)
    ENUMERATOR(DISCORD_SYSTEM, = 1 << 9)
    ENUMERATOR(DISCORD_BUG_HUNTER_LEVEL_2, = 1 << 10)
    ENUMERATOR(DISCORD_VERIFIED_BOT, = 1 << 11)
    ENUMERATOR(DISCORD_EARLY_VERIFIED_BOT_DEVELOPER, = 1 << 12)
ENUM_END(discord_user_flags)

ENUM_BEGIN(discord_premium_types)
    ENUMERATOR(DISCORD_NITRO_CLASSIC, = 0)
    ENUMERATOR(DISCORD_NITRO, )
ENUM_END(discord_premium_types)

STRUCT_BEGIN(discord_user)
  COND_INSERT(id, !=, 0)
    FIELD_PRINTF(u64snowflake, SCNu64, PRIu64, id)
  COND_INSERT(username, !=, NULL)
    FIELD_PTR(char, *, username)
  COND_INSERT(discriminator, !=, NULL)
    FIELD_PTR(char, *, discriminator)
  COND_INSERT(avatar, !=, NULL)
    FIELD_PTR(char, *, avatar)
    FIELD(bool, bot)
    FIELD_CUSTOM(bool, DECOR_BLANK, System, INIT_BLANK, CLEANUP_BLANK, 
                 JSON_ENCODER_bool, JSON_DECODER_bool, system)
    FIELD(bool, mfa_enabled)
  COND_INSERT(locale, !=, NULL)
    FIELD_PTR(char, *, locale)
    FIELD(bool, verified)
  COND_INSERT(email, !=, NULL)
    FIELD_PTR(char, *, email)
    FIELD_ENUM(discord_user_flags, flags)
  COND_INSERT(banner, !=, NULL)
    FIELD_PTR(char, *, banner)
    FIELD_ENUM(discord_premium_types, premium_type)
    FIELD_ENUM(discord_user_flags, public_flags)
STRUCT_END(discord_user)

LIST_BEGIN(discord_users)
    LISTTYPE_STRUCT(discord_user)
LIST_END(discord_users)
